Async Block and Redis Support
xelevra/clearnet pull request #3
Opened 2019-04-10 08:36 UTC by xelevra

2019-04-12 06:06 UTC, programmerr47 requested changes

2019-04-12 06:06 UTC, programmerr47 commented on clearnet/src/main/java/clearnet/interfaces.kt
>      fun executeGet(headers: Map<String, String>, queryParams: Map<String, String> = emptyMap()): Pair<String, Map<String, String>>
Зачем они нужны клиенту класса, который, как я понял теперь исполняет только postAsync или getAsync в методе obtainFromNet?

2019-04-12 06:06 UTC, programmerr47 commented on clearnet/src/main/java/clearnet/error/ConversionException.java
> +        setKind(KIND.CONVERSION);
Почему? :(

2019-04-12 06:06 UTC, programmerr47 commented on clearnet/src/main/java/clearnet/blocks/GetFromNetBlock.kt
> +        if (httpRequestType == "POST") {
А Delete, Put, Patch и Update не будет?

2019-04-15 06:49 UTC, xelevra commented on clearnet/src/main/java/clearnet/interfaces.kt
>      fun executeGet(headers: Map<String, String>, queryParams: Map<String, String> = emptyMap()): Pair<String, Map<String, String>>
Не, не только, я прокомментировал ниже, желательно реализовывать синхронные методы, чтоб вешний сервис не брал на себя работу с пулом потоков. И реализация поумолчанию для getAsync и postAsync заворачивает синхронный запрос в single. Но для некоторых екзекуторов синхронная реализация невозможна, поэтому пришлось оставить рекомендательный характер. В getFromNet блоке, например, для батчей используется синхронная реализация.

2019-04-15 06:51 UTC, xelevra commented on clearnet/src/main/java/clearnet/blocks/GetFromNetBlock.kt
> +        if (httpRequestType == "POST") {
Это по сути дублирующие методы, они по протоколу различаются только типом запроса. По мере надобности, когда кто-то будет добавлять REST, добавим параметр с типом запроса.

2019-04-15 07:01 UTC, xelevra commented on clearnet/src/main/java/clearnet/error/ConversionException.java
> +        setKind(KIND.CONVERSION);
Поправил, перевёл все исключения на котлин

2019-04-15 07:42 UTC, programmerr47 commented on clearnet/src/main/java/clearnet/interfaces.kt
>      fun executeGet(headers: Map<String, String>, queryParams: Map<String, String> = emptyMap()): Pair<String, Map<String, String>>
Я веду к тому, что нельзя ли асинхронные методы выделать в отдельный интерфейс или класс, который оборачивает синхронные методы `IRequestExecutor`-а в `Single`?

2019-04-16 11:22 UTC, xelevra commented on clearnet/src/main/java/clearnet/interfaces.kt
>      fun executeGet(headers: Map<String, String>, queryParams: Map<String, String> = emptyMap()): Pair<String, Map<String, String>>
Готово

2019-04-21 13:14 UTC, atm-13 approved these changes

2019-04-22 06:35 UTC, merged